import { Router } from "express";
import authRoutes from "./auth.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import projectRoutes from "./project.routes.js";
import infrastructureRoutes from "./infrastructure.routes.js";
import profileRoutes from "./profile.routes.js";
import incidentRoutes from "./incident.routes.js";
import deploymentRoutes from "./deployment.routes.js";
import activityRoutes from "./activity.routes.js";
import adminRoutes from "./admin.routes.js";
import grafanaRoutes from "./grafana.routes.js";
import settingsRoutes from "./settings.routes.js";
import credentialRoutes from "./credential.routes.js";
import sslRoutes from "./ssl.routes.js";
import npmRoutes from "./npm.routes.js";
import domainRoutes from "./domain.routes.js";
import serviceRoutes from "./service.routes.js";
import documentRoutes from "./document.routes.js";
import uploadRoutes from "./upload.routes.js";
import notificationRoutes from "./notification.routes.js";
import budgetRoutes from "./budget.routes.js";
import requisitionRoutes from "./requisition.routes.js";
import helpdeskRoutes from "./helpdesk.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/projects", projectRoutes);
router.use("/infrastructure", infrastructureRoutes);
router.use("/profile", profileRoutes);
router.use("/incidents", incidentRoutes);
router.use("/deployments", deploymentRoutes);
router.use("/activity-log", activityRoutes);
router.use("/admin", adminRoutes);
router.use("/grafana", grafanaRoutes);
router.use("/settings", settingsRoutes);
router.use("/projects", credentialRoutes);
router.use("/ssl", sslRoutes);
router.use("/npm", npmRoutes);
router.use("/domains", domainRoutes);
router.use("/services", serviceRoutes);
router.use("/documents", documentRoutes);
router.use("/upload", uploadRoutes);
router.use("/notifications", notificationRoutes);
router.use("/budget", budgetRoutes);
router.use("/requisitions", requisitionRoutes);
router.use("/helpdesk", helpdeskRoutes);

export default router;
